<?php
/**
 * @file
 * Code for the This American Life feature.
 */

include_once 'tal.features.inc';

function tal_permission() {
  return array(
    'administer tal' => array(
      'title' => t('Administer TAL'),
      'description' => t('Update custom settings for This American Life.'),
    ),
    'view schedule' => array(
      'title' => t('View TAL Schedule'),
      'description' => t('Read broadcast schedule and other internal information.'),
    ),
  );
}

function tal_admin_paths() {
  $paths = array(
    'system/tfa/*' => TRUE,
    'user' => TRUE,
    'user/*' => TRUE,
  );
  return $paths;
}

function tal_time_to_seconds($time) {
  $sec = 0;
  foreach (array_reverse(explode(':', $time)) as $k => $v) $sec += pow(60, $k) * $v;
  return $sec;
}

function tal_seconds_to_timecode ($seconds) {
  // get our integers
  $timecode_array = [
    round($seconds / 60, 0, PHP_ROUND_HALF_DOWN),
    $seconds % 60
  ];
  // format integers as strings
  foreach ($timecode_array as $i => $num) {
    $num_str =  strval($num);
    if (strlen($num_str) == 1) $num_str = "0$num_str";
    $timecode_array[$i] = $num_str;
  }
  // compose entire string
  $timecode = implode(':', $timecode_array);

  return $timecode;
}


function tal_rewrite_itunes($link) {
  $parsed = parse_url($link);
  $parsed['host'] = 'geo.itunes.apple.com';
  $path = explode('/', $parsed['path']);
  $last = count($path) - 1;
  $query = array(
    'mt' => 1,
    'at' => '11l6oU',
    'app' => 'itunes',
    'id' => $path[$last],
  );
  if (preg_match('/id(.*)/', $path[$last], $match)) {
    $id = $match[1];
    $query['id'] = $id;
    $path[$last] = $id;
  }
  $link = url('https://'.$parsed['host'].implode('/', $path), array('query' => $query));
  return $link;
}

/**
* Implementation of hook_menu().
*/
function tal_menu() {
  $items = array();

  $items['goto'] = array(
    'page callback' => 'tal_goto_page',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'tal.pages.inc',
  );

  $items['archive'] = array(
    'page callback' => 'tal_archive_page',
    'access arguments' => array('access content'),
    'title' => 'Archive',
    'file' => 'tal.pages.inc',
    'type' => MENU_CALLBACK,
  );

  $items['broadcast'] = array(
    'page callback' => 'tal_broadcast_page',
    'access arguments' => array('access content'),
    'title' => 'Broadcast',
    'file' => 'tal.pages.inc',
    'type' => MENU_CALLBACK,
  );

  $items['broadcast/acts'] = array(
    'page callback' => 'tal_broadcast_acts_page',
    'access arguments' => array('access content'),
    'title' => 'Acts',
    'file' => 'tal.pages.inc',
    'type' => MENU_CALLBACK,
  );

  $items['broadcast/acts.csv'] = array(
    'page callback' => 'tal_broadcast_acts_csv',
    'access arguments' => array('access content'),
    'title' => 'Acts',
    'file' => 'tal.pages.inc',
    'type' => MENU_CALLBACK,
  );

  $items['broadcast/nyt'] = array(
    'page callback' => 'tal_broadcast_nyt_page',
    'access arguments' => array('access content'),
    'title' => 'NYT Episodes',
    'file' => 'tal.pages.inc',
    'type' => MENU_CALLBACK,
  );

  $items['admin/reports/tal/tags'] = array(
    'page callback' => 'tal_tags_report_page',
    'access arguments' => array('administer tal'),
    'title' => 'Tag Reports',
    'file' => 'tal.admin.inc',
    'type' => MENU_CALLBACK,
  );

  $items['admin/reports/tal/producers'] = array(
    'page callback' => 'tal_producers_report_page',
    'access arguments' => array('administer tal'),
    'title' => 'Producers Reports',
    'file' => 'tal.admin.inc',
    'type' => MENU_CALLBACK,
  );

  $items['admin/reports/tal/songs'] = array(
    'page callback' => 'tal_songs_report_page',
    'access arguments' => array('administer tal'),
    'title' => 'Producers Reports',
    'file' => 'tal.admin.inc',
    'type' => MENU_CALLBACK,
  );

  $items['admin/reports/tal/images'] = array(
    'page callback' => 'tal_images_report_page',
    'access arguments' => array('administer tal'),
    'title' => 'Producers Reports',
    'file' => 'tal.admin.inc',
    'type' => MENU_CALLBACK,
  );

  $items['admin/reports/tal/nyt'] = array(
    'page callback' => 'tal_nyt_report_page',
    'access arguments' => array('administer tal'),
    'title' => 'NYT Reports',
    'file' => 'tal.admin.inc',
    'type' => MENU_CALLBACK,
  );

  $items['admin/reports/tal/acts'] = array(
    'page callback' => 'tal_acts_report_page',
    'access arguments' => array('administer tal'),
    'title' => 'Acts Reports',
    'file' => 'tal.admin.inc',
    'type' => MENU_CALLBACK,
  );

  $items['admin/reports/tal/archive/mp3s'] = array(
    'page callback' => 'tal_archive_csv',
    'access arguments' => array('administer tal'),
    'title' => 'Archive',
    'file' => 'tal.admin.inc',
    'type' => MENU_CALLBACK,
  );

  $items['admin/content-advisory'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tal_content_advisory_form'),
    'access arguments' => array('administer tal'),
    'title' => 'Content Advisory',
    'file' => 'tal.admin.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function tal_page_alter(&$page) {
  if ($node = menu_get_object()) {
    switch ($node->type) {
      case 'collection':
      case 'video_collection':
      case 'about':
      case 'episode':
      case 'article':
      case 'video':
      case 'announcement':
      case 'tv':
      case 'fullscreen':
      case 'pick':
      case 'page':
      case 'landing':
        $image = false;
        if ($items = field_get_items('node', $node, 'field_social_image')) {
          $image = file_create_url($items[0]['uri']);
        }
        else if ($items = field_get_items('node', $node, 'field_image')) {
          $image = file_create_url($items[0]['uri']);
        }
        if (!empty($image)) {
          $image_width = (int) $items[0]['width'];
          if ($image_width > 800) {
            $image = image_style_url("metaimage", $items[0]['uri']);
          }
          $page['content']['metatags']['node:'.$node->type]['og:image']['#attached']['drupal_add_html_head'][0][0]['#value'] = $image;
          $page['content']['metatags']['node:'.$node->type]['twitter:image']['#attached']['drupal_add_html_head'][0][0]['#value'] = $image;
        }
        break;

      case 'listen':
        $image = false;
        if ($items = field_get_items('node', $node, 'field_social_image')) {
          $image = file_create_url($items[0]['uri']);
        }
        else if ($items = field_get_items('node', $node, 'field_banner')) {
          $image = file_create_url($items[0]['uri']);
        }
        if (!empty($image)) {
          $page['content']['metatags']['node:'.$node->type]['og:image']['#attached']['drupal_add_html_head'][0][0]['#value'] = $image;
          $page['content']['metatags']['node:'.$node->type]['twitter:image']['#attached']['drupal_add_html_head'][0][0]['#value'] = $image;
        }
        break;

      case 'act':
        $image = false;
        if ($items = field_get_items('node', $node, 'field_social_image')) {
          $image = file_create_url($items[0]['uri']);
        }
        else if ($items = field_get_items('node', $node, 'field_image')) {
          $image = file_create_url($items[0]['uri']);
        }
        else if ($items = field_get_items('node', $node, 'field_episode')) {
          if ($episode = (!empty($items[0]['entity']) ? $items[0]['entity'] : node_load($items[0]['target_id']))) {
            if ($items = field_get_items('node', $episode, 'field_social_image')) {
              $image = file_create_url($items[0]['uri']);
            }
            else if ($items = field_get_items('node', $episode, 'field_image')) {
              $image = file_create_url($items[0]['uri']);
            }
          }
        }
        if (!empty($image)) {
          $image_width = (int) $items[0]['width'];
          if ($image_width > 800) {
            $image = image_style_url("metaimage", $items[0]['uri']);
          }
          $page['content']['metatags']['node:'.$node->type]['og:image']['#attached']['drupal_add_html_head'][0][0]['#value'] = $image;
          $page['content']['metatags']['node:'.$node->type]['twitter:image']['#attached']['drupal_add_html_head'][0][0]['#value'] = $image;
        }
        if ($items = field_get_items('node', $node, 'body')) {
          if (empty($items[0]['summary']) && $body = filter_xss($items[0]['value'], array())) {
            if (preg_match_all('/\.\s+[A-Z\(]+/', $body, $matches, PREG_OFFSET_CAPTURE)) {
              if (!empty($matches[0][0][1])) {
                $body = substr($body, 0, $matches[0][0][1]).'.';
              }
            }
            $page['content']['metatags']['node:'.$node->type]['description']['#attached']['drupal_add_html_head'][0][0]['#value'] = $body;
            $page['content']['metatags']['node:'.$node->type]['og:description']['#attached']['drupal_add_html_head'][0][0]['#value'] = $body;
            $page['content']['metatags']['node:'.$node->type]['twitter:description']['#attached']['drupal_add_html_head'][0][0]['#value'] = $body;
          }
        }
        break;
    }
  }
  else if (arg(0) == 'archive') {
    $description = t('Browse more than 600 episodes, and find your favorite stories by topic, contributor, and year.');
    $element = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'name' => 'description',
        'content' => $description,
      ),
    );
    drupal_add_html_head($element, drupal_html_class('description'));
    $element = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'name' => 'twitter:description',
        'content' => $description,
      ),
    );
    drupal_add_html_head($element, drupal_html_class('twitter:description'));
    $element = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'property' => 'og:description',
        'content' => $description,
      ),
    );
    drupal_add_html_head($element, drupal_html_class('og:description'));
    $image = url('sites/all/themes/thislife/img/archive.jpg', array('absolute' => true));
    if (!empty($image)) {
      $page['content']['metatags']['global']['og:image']['#attached']['drupal_add_html_head'][0][0]['#value'] = $image;
    }
  }
  else if (request_path() == 'about/staff') {
    $description = t('Meet the people who make our show.');
    $element = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'name' => 'description',
        'content' => $description,
      ),
    );
    drupal_add_html_head($element, drupal_html_class('description'));
    $element = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'name' => 'twitter:description',
        'content' => $description,
      ),
    );
    drupal_add_html_head($element, drupal_html_class('twitter:description'));
    $element = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'property' => 'og:description',
        'content' => $description,
      ),
    );
    drupal_add_html_head($element, drupal_html_class('og:description'));
  }
  else if (request_path() == 'about/announcements') {
    $description = t('Updates on the show.');
    $element = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'name' => 'description',
        'content' => $description,
      ),
    );
    drupal_add_html_head($element, drupal_html_class('description'));
    $element = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'name' => 'twitter:description',
        'content' => $description,
      ),
    );
    drupal_add_html_head($element, drupal_html_class('twitter:description'));
    $element = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'property' => 'og:description',
        'content' => $description,
      ),
    );
    drupal_add_html_head($element, drupal_html_class('og:description'));
  }
}

function tal_share_url($service, $node = null) {
  if (!empty($node)) {
    $url = url('node/'.$node->nid, array('absolute' => true));
  }
  elseif (drupal_is_front_page()) {
    $url = url('<front>', array('absolute' => true));
  }
  else {
    $url = url(current_path(), array('absolute' => true));
  }
  switch ($service) {
    case 'facebook':
      $query = array(
        'u' => $url,
      );
      return url('https://www.facebook.com/sharer/sharer.php', array('query' => $query));
      break;

    case 'twitter':
      if (!empty($node)) {
        $title = $node->title;
      }
      elseif (drupal_is_front_page()) {
        $title = variable_get('site_name');
      }
      else {
        $title = drupal_get_title();
      }
      $query = array(
        'text' => t('!title !url', array('!title' => $title, '!url' => $url)),
      );
      return url('https://x.com/intent/tweet', array('query' => $query));
      break;

    case 'mail':
      if (!empty($node)) {
        $subject = t('!sitename: !title', array('!sitename' => variable_get('site_name'), '!title' => $node->title));
      }
      elseif (drupal_is_front_page()) {
        $subject = variable_get('site_name');
      }
      else {
        $subject = t('!sitename: !title', array('!sitename' => variable_get('site_name'), '!title' => drupal_get_title()));
      }
      $body = array();
      $body[] = $url;
      $mailto = array(
        'subject' => $subject,
        'body' => implode("\n\n", $body),
      );
      return url('mailto:', array('query' => $mailto));
      break;
  }
}

function tal_load_import($id) {
  if ($result = db_query("SELECT entity_type, entity_id FROM {field_data_field_import_id} i WHERE i.field_import_id_value = :id", array(':id' => $id))->fetchObject()) {
    $ids = array($result->entity_id);
    $entity_type = $result->entity_type;
    $entity = entity_load($entity_type, $ids);
    return reset($entity);
  }
  return false;
}

function tal_form_alter(&$form, &$form_state, $form_id) {
  $path = drupal_get_path('module', 'tal');
  if ($form_id == 'file_entity_edit' || $form_id == 'file_entity_add_upload') {
    $form['#attached']['css'][] = $path.'/css/tal.node-form.css';
    if (!empty($form['field_caption'][LANGUAGE_NONE][0])) {
      $form['field_caption'][LANGUAGE_NONE][0]['#format'] = 'simple';
    }
    if (!empty($form['field_credit'][LANGUAGE_NONE][0])) {
      $form['field_credit'][LANGUAGE_NONE][0]['#format'] = 'simple';
    }
  }
  elseif ($form_id == 'video_collection_node_form') {
    if (!empty($form['body'][LANGUAGE_NONE][0])) {
      $form['body'][LANGUAGE_NONE][0]['#format'] = 'simple';
    }
  }
}

/**
* undocumented function
*/
function tal_form_node_form_alter(&$form, &$form_state) {
  $path = drupal_get_path('module', 'tal');
  //$form['#attached']['js'][] = $path.'/js/tal.node-form.js';
  $form['#attached']['css'][] = $path.'/css/tal.node-form.css';
  $node = $form['#node'];

  unset($form['options']['sticky']);
  unset($form['options']['promote']);

  //$form['title']['#required'] = false;

  if (in_array($node->type, array('page', 'episode', 'act', 'article', 'gallery', 'video', 'announcement', 'tv', 'tv_act', 'collection', 'video_collection', 'pick', 'landing'))) {
    unset($form['body'][LANGUAGE_NONE][0]['summary']['#description']);
    $form['body'][LANGUAGE_NONE][0]['summary']['#title'] = t('Short Description');
    if (!empty($form['body'][LANGUAGE_NONE][0]['summary']['#attached']['js'])) {
      foreach ($form['body'][LANGUAGE_NONE][0]['summary']['#attached']['js'] as $id => $js_file) {
        if ($js_file == 'modules/field/modules/text/text.js') {
          unset($form['body'][LANGUAGE_NONE][0]['summary']['#attached']['js'][$id]);
        }
      }
    }
  }
  else if (!empty($form['body'][LANGUAGE_NONE][0]['summary'])) {
    $form['body'][LANGUAGE_NONE][0]['summary']['#access'] = false;
  }
}

function tal_node_update($node) {
  $node_link = l(t('view'), 'node/' . $node->nid);
  $watchdog_args = array('@type' => $node->type, '%title' => $node->title);
  $t_args = array('@type' => node_type_get_name($node), '%title' => $node->title);
  watchdog('debug', '@type: saved %title.', $watchdog_args, WATCHDOG_NOTICE, $node_link);
}

function tal_node_presave($node) {
  /*
  if ($items = field_get_items('node', $node, 'field_publication_date')) {
    $node->created = $items[0]['value'];
  }
  */
}

function tal_node_view_alter(&$build) {
  if (isset($build['#node'])) {
    $node = $build['#node'];
    if (!empty($node->nid)) {
      $build['#contextual_links']['node'] = array('node', array($node->nid));
    }
  }
}

function tal_node_view($node, $view_mode, $langcode) {
  drupal_add_library('contextual', 'contextual-links');
  if ($node->type == 'listen') {
    if ($view_mode == 'full') {
      if (!empty($node->content['field_podcast_body'][0]['#markup'])) {
        $body = $node->content['field_podcast_body'][0]['#markup'];
        if (preg_match_all('/<p>\[(?!\/)(\w*)([^\]]+)?\](([^\[]*)\[\/\1\])?<\/p>/uis', $body, $matches, PREG_SET_ORDER)) {
          foreach ($matches as $match) {
            switch ($match[1]) {
              case 'apps':
              case 'list':
              case 'app_list':
              case 'app-list':
              $find = $match[0];
              $items = array(
                array(
                  'children' => array(
                    array('data' => l('<span>'.t('Apple Podcasts').'</span>', 'https://podcasts.apple.com/us/podcast/this-american-life/id201671138?itscg=30200&itsct=podcast_box&ls=1&mttnsubad=201671138&at=1001lJHP&ct=thisamericanlife.org+-+How+To+Listen', array('html' => true)), 'class' => array('apple-podcasts')),
                  ),
                ),
                array(
                  'children' => array(
                    array('data' => l('<span>'.t('Spotify').'</span>', 'https://open.spotify.com/show/41zWZdWCpVQrKj7ykQnXRc', array('html' => true)), 'class' => array('spotify')),
                  ),
                ),
                array(
                  'children' => array(
                    array('data' => l('<span>'.t('YouTube').'</span>', 'https://www.youtube.com/@this-american-life', array('html' => true)), 'class' => array('youtube')),
                  ),
                ),
              );
              $replace = theme('item_list', array('items' => $items, 'attributes' => array('class' => array('clearfix'))));
              $body = str_replace($find, $replace, $body);
              break;
            }
          }
        }
        $node->content['field_podcast_body'][0]['#markup'] = $body;
      }
    }
  }

  if ($view_mode == 'full') {
    if (!empty($node->content['body'][0]['#markup'])) {
      $body = $node->content['body'][0]['#markup'];
      $count = 0;

      if (preg_match_all('/<p>\[(?!\/)(\w*)([^\]]+)?\](([^\[]*)\[\/\1\])?<\/p>/uis', $body, $matches, PREG_SET_ORDER)) {
        foreach ($matches as $match) {
          switch ($match[1]) {


          }
        }
      }

      while (preg_match('/<p[^>]*>(?<!")(https?:\/\/[^<\s"]*)(?!")<\/p>/', $body, $matches, PREG_OFFSET_CAPTURE)) {
        $count++;
        if ($count > 25) {
          break;
        }
        $find = trim($matches[1][0]);
        if ($replace = tal_oembed($find, true)) {
          $body = substr_replace($body, $replace, $matches[0][1], strlen($matches[0][0]));
        }
      }
      $node->content['body'][0]['#markup'] = $body;
    }
  }
}

function tal_apachesolr_field_name_map_alter(&$map) {
  $map['ts_transcript'] = t('Transcript');
}

function tal_apachesolr_index_document_build_node($document, $entity, $env_id) {
  $type = false;
  if ($items = field_get_items('node', $entity, 'field_contributor')) {
    foreach ($items as $item) {
      $document->addField('im_credits', $item['target_id']);
    }
  }
  if ($credits = field_get_items('node', $entity, 'field_credits')) {
    foreach ($credits as $credit) {
      if ($field_collection_item = field_collection_item_load($credit['value'])) {
        if ($items = field_get_items('field_collection_item', $field_collection_item, 'field_contributor')) {
          foreach ($items as $item) {
            $document->addField('im_credits', $item['target_id']);
          }
        }
      }
    }
  }
  switch ($entity->type) {
    case 'announcement':
    $type = 'announcements';
    break;
    case 'tv':
    $type = 'tv';
    break;
    case 'act':
    if ($items = field_get_items('node', $entity, 'field_episode')) {
      if ($episode = node_load($items[0]['target_id'])) {
        $act_number = null;
        if ($items = field_get_items('node', $episode, 'field_radio_air_date')) {
          $document->addField('is_year', date('Y', strtotime($items[0]['value'])));
          $document->addField('ds_field_radio_air_date', apachesolr_date_iso(strtotime($items[0]['value'])));
        }
        if ($items = field_get_items('node', $entity, 'field_act_number')) {
          $act_number = $items[0]['value'];
          $query = db_select('node', 'n');
          $query->join('field_data_field_episode', 'e', "(e.entity_id = n.nid AND e.entity_type ='node' AND e.deleted = 0)");
          $query
            ->fields('n', array('nid'))
            ->condition('e.field_episode_target_id', $episode->nid)
            ->condition('n.status', 1)
            ->condition('n.type', 'transcript');
          if ($nid = $query->execute()->fetchField()) {
            $transcript = node_load($nid);
            if ($items = field_get_items('node', $transcript, 'field_transcript_xml')) {
              $render = array();
              $contents = $items[0]['value'];
              $contents = str_replace(array('<i></i>', 'AT&T', '&lt;i&gt;', '&lt;/i&gt;'), array('', 'AT&amp;T', '<i>', '</i>'), $contents);
              $xml = simplexml_load_string($contents);
              $xml = $xml->body;
              $acts = $xml->act;
              if (!empty($acts)) {
                $total_acts = count($acts);
                $act_count = 0;
                foreach ($acts as $act) {
                  if (!empty($act->speaker)) {
                    if ($act_count == $act_number) {
                      $render[] = array(
                        '#theme' => 'tal_transcript_act',
                        '#act' => $act,
                        '#node' => $episode,
                        '#count' => $act_count,
                        '#total_acts' => $total_acts,
                      );
                    }
                    $act_count++;
                  }
                }
              }
            }
            $transcript = render($render);
            $transcript = str_replace('><', '> <', $transcript);
            $transcript = filter_xss($transcript, array());
            $document->addField('ts_transcript', $transcript);
          }
        }
      }
    }
    case 'episode':
    $type = 'episodes';
    break;
    case 'gallery':
    case 'article':
    case 'fullscreen':
    $type = 'extras';
    break;
    case 'video':
    $type = 'videos';
    break;
  }
  $document->addField('ss_type', $type);
  $document->addField('ss_type_filter', $type);
  if ($items = field_get_items('node', $entity, 'field_radio_air_date')) {
    $document->addField('is_year', date('Y', strtotime($items[0]['value'])));
    $document->addField('ds_field_radio_air_date', apachesolr_date_iso(strtotime($items[0]['value'])));
  }
}

/**
* Implementation of hook_theme().
*/
function tal_theme($existing, $type, $theme, $path) {
  return array(
    'tal_media_image' => array(
      'variables' => array('file' => null, 'view_mode' => null, 'alignment' => null),
      'template' => 'tal-media-image',
      'path' => $path.'/templates',
    ),
  );
}

/**
 * Implements hook_wysiwyg_editor_settings_alter()
 */
function tal_wysiwyg_editor_settings_alter(&$settings, $context) {
  if ($context['profile']->editor == 'ckeditor') {
    $settings['extraPlugins'] = 'media,codemirror';
    $settings['resize_enabled'] = true;
  }
}


 function tal_media_wysiwyg_token_to_markup_alter(&$element, $tag_info, $settings) {
   $element['content'] = array(
     '#theme' => 'tal_media_image',
     '#file' => $tag_info['file'],
     '#view_mode' => $tag_info['view_mode'],
     '#alignment' => $tag_info['fields']['alignment'],
   );
 }

 /**
 * undocumented function
 */
 function template_preprocess_tal_media_image(&$variables) {
   $variables['classes_array'][] = 'clearfix';
   $file = $variables['file'];
   $view_mode = $variables['view_mode'];
   $alignment = $variables['alignment'];
   $variables['classes_array'][] = drupal_html_class($view_mode);
   $variables['classes_array'][] = drupal_html_class($alignment);

   $variables['image'] = file_view_file($file, $view_mode);

   $caption = array();
   // Caption
   if ($items = field_get_items('file', $file, 'field_caption')) {
     if (!empty($items[0]['value'])) {
       $caption['caption'] = array(
         '#markup' => check_markup($items[0]['value'], 'simple'),
       );
     }
   }
   if ($items = field_get_items('file', $file, 'field_credit')) {
     if (!empty($items[0]['value'])) {
       $caption['credit'] = array(
         '#prefix' => '<div class="credit">',
         '#suffix' => '</div>',
         '#markup' => check_markup($items[0]['value'], 'simple'),
       );
     }
   }
   if (!empty($caption)) {
     $variables['caption'] = $caption;
   }
 }

/**
* Implements hook_media_format_form_prepare_alter().
*/
function tal_media_wysiwyg_format_form_prepare_alter(&$form, $form_state, $file) {
  $form['options']['#title'] = t('Layout Options');
  $form['options']['format']['#title'] = t('Width');
  //$form['options']['format']['#options']['default'] = t('Full');
  //$form['options']['format']['#options']['teaser'] = t('Half');
  unset($form['options']['format']['#description'], $form['options']['alignment']['#description'], $form['options']['alignment']['#options']['center']);
}

/**
* Implements hook_entity_info_alter().
*/
function tal_entity_info_alter(&$entity_info) {
  $entity_info['file']['view modes']['inset'] = array(
    'label' => t('Inset'),
    'custom settings' => TRUE,
  );
  $entity_info['file']['view modes']['vertical'] = array(
    'label' => t('Vertical'),
    'custom settings' => TRUE,
  );
  $entity_info['file']['view modes']['bleed'] = array(
    'label' => t('Full bleed'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['related'] = array(
    'label' => t('Related'),
    'custom settings' => FALSE,
  );
  $entity_info['node']['view modes']['collection'] = array(
    'label' => t('Collection'),
    'custom settings' => FALSE,
  );
  $entity_info['node']['view modes']['landing'] = array(
    'label' => t('Landing'),
    'custom settings' => FALSE,
  );
  $entity_info['field_collection_item']['view modes']['landing'] = array(
    'label' => t('Landing'),
    'custom settings' => FALSE,
  );
  $entity_info['node']['view modes']['homepage'] = array(
    'label' => t('Homepage'),
    'custom settings' => FALSE,
  );
  $entity_info['node']['view modes']['featured'] = array(
    'label' => t('Featured'),
    'custom settings' => FALSE,
  );
  $entity_info['node']['view modes']['recently'] = array(
    'label' => t('Recently Aired'),
    'custom settings' => FALSE,
  );
  $entity_info['node']['view modes']['series'] = array(
    'label' => t('Series'),
    'custom settings' => FALSE,
  );
  $entity_info['node']['view modes']['archive'] = array(
    'label' => t('Archive'),
    'custom settings' => FALSE,
  );
  $entity_info['node']['view modes']['footer'] = array(
    'label' => t('Footer'),
    'custom settings' => FALSE,
  );
}

function tal_field_formatter_info() {
  return array(
    'summary_only_formatter' => array(
      'label' => t('Summary only'),
      'field types' => array('text_with_summary'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function tal_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  switch ($display['type']) {
    case 'summary_only_formatter':
      $element = array();
      foreach ($items as $item){
        if (isset($item['summary']) && !empty($item['summary'])) {
            $element[]['#markup'] = $item['summary'];
        }
      }
      return $element;
      break;
  }
}

function tal_apachesolr_query_prepare($query) {
  $query->setAvailableSort('ds_field_radio_air_date', array('title' => t('Date'), 'default' => 'desc'));
  $query->setAvailableSort('its_field_act_number', array('title' => t('Act'), 'default' => 'asc'));
  $query->removeAvailableSort('score');
  $query->removeAvailableSort('sort_label');
  $query->removeAvailableSort('bundle');
  $query->removeAvailableSort('sort_name');
  $query->removeAvailableSort('ds_created');
}

/**
 * undocumented function
 */
function tal_search_results() {
  drupal_static_reset('apachesolr_static_response_cache');
  $per_page = 24;
  $nodes = array();
  $search_page = array(
    'page_id' => 'archive',
    'label' => t('Archive'),
    'description' => '',
    'search_path' => current_path(),
    'page_title' => t('Archive'),
    'env_id' => 'solr',
    'settings' => array(
      'fq' => array(),
      'apachesolr_search_search_type' => 'bundle',
      'apachesolr_search_search_box' => 0,
      'apachesolr_search_per_page' => $per_page,
      'apachesolr_search_browse' => 'results',
      'apachesolr_search_spellcheck' => 0,
      'apachesolr_search_allow_user_input' => 0,
    ),
  );
  $search_page = (object) $search_page;
  $filtered = false;

  if (!empty($_GET['keyword'])) {
    $filtered = true;
    if (is_array($_GET['keyword'])) {
      $strings = array();
      foreach ($_GET['keyword'] as $key) {
        $strings[] = strtolower(filter_xss($key, array()));
      }
      $keys = '('.implode(' AND ', $strings).')';
    }
    else {
      $keys = strtolower(filter_xss($_GET['keyword']));
    }
  }

  $conditions = array(
    'fq' => array(
      'bs_status:true',
    ),
  );

  $params = array(
    'facet' => 'true',
    'facet.mincount' => 1,
    'facet.field' => array(),
  );

  $params['facet.field'][] = '{!ex=dt}ss_type_filter';
  $params['facet.field'][] = 'ss_type';
  $options = array(
    'episodes' => t('Episodes'),
    'videos' => t('Videos'),
    'extras' => t('Extras'),
    'tv' => t('TV Show'),
  );
  if (!empty($_GET['type']) && is_string($_GET['type']) && isset($options[$_GET['type']])) {
    $conditions['fq'][] = '{!tag=dt}ss_type_filter:'.filter_xss($_GET['type'], array());
    $filtered = true;
  }
  $params['facet.field'][] = '{!ex=y}is_year';
  if (!empty($_GET['year']) && is_numeric($_GET['year']) && $_GET['year'] >= 1995 && $_GET['year'] <= date('Y')) {
    $conditions['fq'][] = '{!tag=y}is_year:'.$_GET['year'];
    $filtered = true;
  }
  if ($vocab = taxonomy_vocabulary_machine_name_load('contributor')) {
    $params['facet.field'][] = 'im_credits';
    if (!empty($_GET['contributor']) && is_numeric($_GET['contributor'])) {
      $conditions['fq'][] = 'im_credits:'.$_GET['contributor'];
      $filtered = true;
    }
  }
  if ($vocab = taxonomy_vocabulary_machine_name_load('tags')) {
    $params['facet.field'][] = 'im_vid_2';
    if (!empty($_GET['tag']) && is_numeric($_GET['tag'])) {
      $conditions['fq'][] = 'im_vid_2:'.$_GET['tag'];
      $filtered = true;
    }
  }
  if (empty($keys)) {
    $conditions['apachesolr_search_sort'] = 'ds_field_radio_air_date desc';
  }
  if ($filtered) {
    $node_types = array('act', 'article', 'gallery', 'video', 'tv', 'fullscreen');
  }
  else {
    $node_types = array('episode', 'article', 'gallery', 'video', 'tv', 'fullscreen');
  }
  $conditions['fq'][] = 'bundle:('.implode(' OR ', $node_types).')';

  $solrsort = isset($conditions['apachesolr_search_sort']) ? $conditions['apachesolr_search_sort'] : '';

  $results = array();
  try {
    $solr = apachesolr_get_solr($search_page->env_id);
    $params['fq'] = isset($conditions['fq']) ? $conditions['fq'] : array();
    $params['rows'] = $search_page->settings['apachesolr_search_per_page'];
    $params['spellcheck'] = empty($search_page->settings['apachesolr_search_spellcheck']) ? 'false' : 'true';

    if (!empty($keys)) {
      $params['q'] = $keys;
    }

    // Hardcoded apachesolr name since we rely on this for the facets
    $results = apachesolr_search_run('apachesolr', $params, $solrsort, $search_page->search_path, pager_find_page(), $solr);
  }
  catch (Exception $e) {
    watchdog('Apache Solr', nl2br(check_plain($e->getMessage())), NULL, WATCHDOG_ERROR);
    apachesolr_failure(t('Solr search'), json_encode($params));
  }

  if ($results) {
    foreach ($results as $result) {
      if (!empty($result['node'])) {
        if (($node = node_load($result['node']->entity_id)) && !empty($node->status)) {
          $nodes[$node->nid] = $node;
        }
      }
    }
  }
  return $nodes;
}


/**
* Helper function to check whether a request is via AJAX
*/
function tal_is_ajax($check_post = false) {
  if (!empty($_REQUEST['ajax'])) {
    return true;
  }
  else if (!isset($_SERVER["HTTP_X_REQUESTED_WITH"])) {
    return false;
  }
  else {
    if ($check_post) return (empty($_POST) && strtolower($_SERVER["HTTP_X_REQUESTED_WITH"]) == 'xmlhttprequest');
    else return strtolower($_SERVER["HTTP_X_REQUESTED_WITH"]) == 'xmlhttprequest';
  }
}

function tal_debug($var, $exit = true) {
  print '<pre>';
  print_r($var);
  print '</pre>';
  if ($exit) exit;
}

function tal_yarg($index = NULL, $path = NULL) {
  static $yarguments;

  if (!isset($path)) {
    $path = request_path();
  }
  if (!isset($yarguments[$path])) {
    $yarguments[$path] = explode('/', $path);
  }
  if (!isset($index)) {
    return $yarguments[$path];
  }
  if (isset($yarguments[$path][$index])) {
    return $yarguments[$path][$index];
  }
}

/**
* undocumented function
*/
function tal_oembed($url, $return_html = false) {
  $providers = array(
    '#https://www\.documentcloud\.org/documents/.*#i' => array('https://www.documentcloud.org/api/oembed.{format}', true, 1110),
    '#http://(www\.)?youtube\.com/watch.*#i' => array( 'http://www.youtube.com/oembed', true, 1110),
    '#https://(www\.)?youtube\.com/watch.*#i' => array( 'http://www.youtube.com/oembed?scheme=https', true, 1110),
    '#http://youtu\.be/.*#i' => array( 'http://www.youtube.com/oembed', true, 1110),
    '#https://youtu\.be/.*#i' => array( 'http://www.youtube.com/oembed?scheme=https', true, 1110),
    'http://blip.tv/*' => array( 'http://blip.tv/oembed/', false),
    '#https?://(.+\.)?vimeo\.com/.*#i' => array( 'http://vimeo.com/api/oembed.{format}', true, 1110),
    '#https?://(www\.)?dailymotion\.com/.*#i' => array( 'http://www.dailymotion.com/services/oembed', true),
    'http://dai.ly/*' => array( 'http://www.dailymotion.com/services/oembed', false ),
    '#https?://(www\.)?flickr\.com/.*#i' => array( 'http://www.flickr.com/services/oembed/', true),
    'http://flic.kr/*' => array( 'http://www.flickr.com/services/oembed/', false ),
    '#https?://(.+\.)?smugmug\.com/.*#i' => array( 'http://api.smugmug.com/services/oembed/', true),
    '#https?://(www\.)?hulu\.com/watch/.*#i' => array( 'http://www.hulu.com/api/oembed.{format}', true),
    '#https?://(www\.)?viddler\.com/.*#i' => array( 'http://lab.viddler.com/services/oembed/', true),
    'http://revision3.com/*' => array( 'http://revision3.com/api/oembed/', false ),
    'http://i*.photobucket.com/albums/*' => array( 'http://photobucket.com/oembed',  false ),
    'http://gi*.photobucket.com/groups/*' => array( 'http://photobucket.com/oembed', false ),
    '#https?://(www\.)?scribd\.com/.*#i' => array( 'http://www.scribd.com/services/oembed', true),
    'http://wordpress.tv/*' => array( 'http://wordpress.tv/oembed/', false ),
    '#https?://(.+\.)?polldaddy\.com/.*#i' => array( 'http://polldaddy.com/oembed/', true),
    '#https?://(www\.)?funnyordie\.com/videos/.*#i' => array( 'http://www.funnyordie.com/oembed.{format}', true),
    '#https?://(www\.)?twitter\.com/.+?/status(es)?/.*#i' => array( 'https://api.twitter.com/1/statuses/oembed.{format}', true),
    '#https?://(www\.)?soundcloud\.com/.*#i' => array( 'http://soundcloud.com/oembed?format={format}', true),
    '#https?://(www\.)?slideshare\.net/*#' => array( 'http://www.slideshare.net/api/oembed/2', true),
    '#http://instagr(\.am|am\.com)/p/.*#i' => array( 'http://api.instagram.com/oembed', true),
    '#https?://(www\.)?rdio\.com/.*#i' => array( 'http://www.rdio.com/api/oembed/', true),
    '#https?://rd\.io/x/.*#i' => array( 'http://www.rdio.com/api/oembed/', true),
    '#https?://(open|play)\.spotify\.com/.*#i' => array( 'https://embed.spotify.com/oembed/', true),
      '#https?://(.+\.)?imgur\.com/.*#i' => array( 'http://api.imgur.com/oembed', true),
      '#https?://(www\.)?meetu(\.ps|p\.com)/.*#i' => array( 'http://api.meetup.com/oembed', true),
      'http://www.kickstarter.com/projects/*' => array('http://www.kickstarter.com/services/oembed', false),
    );
    foreach ($providers as $matchmask => $data) {
      list($providerurl, $regex) = $data;
      // Turn the asterisk-type provider URLs into regex
      if (!$regex) {
        $matchmask = '#' . str_replace( '___wildcard___', '(.+)', preg_quote( str_replace( '*', '___wildcard___', $matchmask ), '#' ) ) . '#i';
        $matchmask = preg_replace( '|^#http\\\://|', '#https?\://', $matchmask );
      }
      if (preg_match($matchmask, $url)) {
        $provider = str_replace('{format}', 'json', $providerurl); // JSON is easier to deal with than XML
        if (!empty($data[2])) {
          $width = $data[2];
        }
        break;
      }
    }
    if (!empty($provider)) {
      $data = array(
        'url' => $url,
        'api' => true,
        //'maxwidth' => (!empty($width) ? $width : '740'),
      );
      $request_url = $provider.(strpos($provider, '?') !== false ? '&' : '?').drupal_http_build_query($data);
      $request = drupal_http_request($request_url);
      if ($request->code == 200) {
        $html = '';
        $data = json_decode($request->data);
        if ($data->type == 'video') {
          if ($data->provider_name == 'YouTube') {
            if (preg_match('/src="([^"]*)"/', $data->html, $matches)) {
              $data->html = str_replace($matches[1], $matches[1]."&showinfo=0", $data->html);
            }
          }
          else if ($data->provider_name == 'Vimeo') {
            if (preg_match('/src="([^"]*)"/', $data->html, $matches)) {
              $data->html = str_replace($matches[1], $matches[1]."&title=0&byline=0", $data->html);
            }
          }
        }
        if ($return_html) {
          if ($data->type == 'video') {
            $html = '<div class="video">'.$data->html.'</div>';
          }
          else if ($data->type == 'photo') {
            $variables = array(
              'path' => $data->url,
            );
            if (!empty($data->title)) {
              $varaibles['title'] = $data->title;
            }
            $html = theme('image', $variables);
          }
          else if (!empty($data->html)) {
            $html = '<div class="rich">'.$data->html.'</div>';
          }
          return $html;
        }
        return $data;
      }
    }
    return false;
  }

  /**
  * undocumented function
  */
  function tal_us_states($state = null) {
    $states = array(
      'AL' => 'Alabama',
      'AK' => 'Alaska',
      'AZ' => 'Arizona',
      'AR' => 'Arkansas',
      'CA' => 'California',
      'CO' => 'Colorado',
      'CT' => 'Connecticut',
      'DE' => 'Delaware',
      'DC' => 'District of Columbia',
      'FL' => 'Florida',
      'GA' => 'Georgia',
      'HI' => 'Hawaii',
      'ID' => 'Idaho',
      'IL' => 'Illinois',
      'IN' => 'Indiana',
      'IA' => 'Iowa',
      'KS' => 'Kansas',
      'KY' => 'Kentucky',
      'LA' => 'Louisiana',
      'ME' => 'Maine',
      'MD' => 'Maryland',
      'MA' => 'Massachusetts',
      'MI' => 'Michigan',
      'MN' => 'Minnesota',
      'MS' => 'Mississippi',
      'MO' => 'Missouri',
      'MT' => 'Montana',
      'NE' => 'Nebraska',
      'NV' => 'Nevada',
      'NH' => 'New Hampshire',
      'NJ' => 'New Jersey',
      'NM' => 'New Mexico',
      'NY' => 'New York',
      'NC' => 'North Carolina',
      'ND' => 'North Dakota',
      'OH' => 'Ohio',
      'OK' => 'Oklahoma',
      'OR' => 'Oregon',
      'PA' => 'Pennsylvania',
      'RI' => 'Rhode Island',
      'SC' => 'South Carolina',
      'SD' => 'South Dakota',
      'TN' => 'Tennessee',
      'TX' => 'Texas',
      'UT' => 'Utah',
      'VT' => 'Vermont',
      'VA' => 'Virginia',
      'WA' => 'Washington',
      'WV' => 'West Virginia',
      'WI' => 'Wisconsin',
      'WY' => 'Wyoming',
    );
    if (!empty($state)) {
      if (!empty($states[$state])) {
        return $states[$state];
      }
      else {
        return false;
      }
    }
    return $states;
  }
