<?php
/**
 * @file
 * Code for the Recommendations feature.
 */

include_once 'tal_recommendation.features.inc';

function tal_recommendation_get_pick_collection() {
  $query = db_select('node', 'n');
  $query
    ->fields('n', array('nid'))
    ->condition('n.type', 'pick_collection')
    ->condition('n.status', 1)
    ->condition('n.created', REQUEST_TIME, '<')
    ->orderBy('n.created', 'DESC')
    ->range(0,1);
  if ($nid = $query->execute()->fetchField()) {
    if ($node = node_load($nid)) {
      return $node;
    }
  }
  return false;
}

function tal_recommendation_node_view($node, $view_mode, $langcode) {
  global $base_url;
  if ($node->type == 'pick') {
    if ($view_mode == 'full') {
      if (!empty($node->content['body'][0]['#markup'])) {
        $body = $node->content['body'][0]['#markup'];
        if (preg_match_all('/<a[^>]*>/', $body, $links)) {
          foreach ($links[0] as $i => $tag) {
            if (preg_match_all('/href="([^"]*)"/', $tag, $matches)) {
              foreach ($matches[1] as $delta => $match) {
                $replace = false;
                $alias = false;
                if ($match[0] == '/') {
                  $alias = substr($match, 1);
                }
                else if (strpos($match, $base_url) === 0) {
                  $alias = str_replace($base_url.base_path(), '', $match);
                }
                if (!empty($alias)) {
                  $path = drupal_get_normal_path($alias);
                  if ($path != $alias) {
                    if ($object = menu_get_object('node', 1, $path)) {
                      if ($object->type == 'episode') {
                        if (preg_match_all('/class="([^"]*)"/', $tag, $matches)) {
                          $attrs = explode(' ', $matches[1][0]);
                          if (!array_search('goto', $attrs)) {
                            $attrs[] = 'goto';
                          }
                          if (!array_search('goto-episode', $attrs)) {
                            $attrs[] = 'goto-episode';
                          }
                          $tag = str_replace($matches[0][0], 'class="'.implode(' ', $attrs).'"', $tag);
                        }
                        else {
                          $tag = str_replace('>', ' class="goto goto-episode">', $tag);
                        }
                        if ($items = field_get_items('node', $object, 'field_episode_number')) {
                          $episode_number =  $items[0]['value'];
                          if (preg_match_all('/data-episode="([^"]*)"/', $tag, $matches)) {
                            $tag = str_replace($matches[0][0], 'data-episode="'.$episode_number.'"', $tag);
                          }
                          else {
                            $tag = str_replace('>', ' data-episode="'.$episode_number.'">', $tag);
                          }
                        }
                      }
                      else if ($object->type == 'act') {
                        if (preg_match_all('/class="([^"]*)"/', $tag, $matches)) {
                          $attrs = explode(' ', $matches[1][0]);
                          if (!array_search('goto', $attrs)) {
                            $attrs[] = 'goto';
                          }
                          if (!array_search('goto-act', $attrs)) {
                            $attrs[] = 'goto-act';
                          }
                          $tag = str_replace($matches[0][0], 'class="'.implode(' ', $attrs).'"', $tag);
                        }
                        else {
                          $tag = str_replace('>', ' class="goto goto-act">', $tag);
                        }
                        if ($items = field_get_items('node', $object, 'field_episode')) {
                          $episode = (!empty($items[0]['entity']) ? $items[0]['entity'] : node_load($items[0]['target_id']));
                          if (preg_match_all('/data-episode-id="([^"]*)"/', $tag, $matches)) {
                            $tag = str_replace($matches[0][0], 'data-episode-id="'.$episode->nid.'"', $tag);
                          }
                          else {
                            $tag = str_replace('>', ' data-episode-id="'.$episode->nid.'">', $tag);
                          }
                          if ($items = field_get_items('node', $episode, 'field_episode_number')) {
                            $episode_number =  $items[0]['value'];
                            if (preg_match_all('/data-episode="([^"]*)"/', $tag, $matches)) {
                              $tag = str_replace($matches[0][0], 'data-episode="'.$episode_number.'"', $tag);
                            }
                            else {
                              $tag = str_replace('>', ' data-episode="'.$episode_number.'">', $tag);
                            }
                          }
                        }
                      }
                      if (preg_match_all('/data-type="([^"]*)"/', $tag, $matches)) {
                        $tag = str_replace($matches[0][0], 'data-type="'.$object->type.'"', $tag);
                      }
                      else {
                        $tag = str_replace('>', ' data-type="'.$object->type.'">', $tag);
                      }
                      if (preg_match_all('/data-id="([^"]*)"/', $tag, $matches)) {
                        $tag = str_replace($matches[0][0], 'data-id="'.$object->nid.'"', $tag);
                      }
                      else {
                        $tag = str_replace('>', ' data-id="'.$object->nid.'">', $tag);
                      }
                    }
                  }
                }
                $body = str_replace($links[0][$i], $tag, $body);
              }
            }
          }
        }
        $node->content['body'][0]['#markup'] = $body;
      }
    }
  }

  if (empty($_GET['app']) && (in_array($node->type, array('collection', 'video_collection', 'pick')))) {
    if ($view_mode == 'full') {
      if ($path = drupal_get_normal_path('recommended')) {
        if ($recommended = menu_get_object('node', 1, $path)) {
          if ($recommended->type == 'collection_landing') {
            $count = 0;
            $i =0;
            foreach (array('field_featured_collections', 'field_collections', 'field_secondary_collections') as $field) {
              if ($items = field_get_items('node', $recommended, $field)) {
                foreach ($items as $item) {
                  $i++;
                  if ($item['target_id'] != $node->nid && $collection = node_load($item['target_id'])) {
                    $node->content['related'][] = node_view($collection, 'collection');
                    $count++;
                    if ($count >= 2) {
                      break 2;
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  if ($node->type == 'video') {
    if ($view_mode == 'full') {
      if ($path = drupal_get_normal_path('videos')) {
        if ($collection = menu_get_object('node', 1, $path)) {
          if ($collection->type == 'video_collection') {
            $exclude = array($node->nid => $node->nid);
            $count = 0;
            $query = db_select('field_data_field_featured_video', 'fv');
            $query->join('field_data_field_videos', 'v', "(fv.entity_id = v.field_videos_value AND fv.entity_type ='field_collection_item')");
            $query
              ->fields('fv', array('entity_id'))
              ->condition('v.entity_id', $collection->nid)
              ->condition('fv.field_featured_video_target_id', $node->nid)
              ->orderBy('fv.delta', 'ASC');;
            if ($fcid = $query->execute()->fetchField()) {
              if ($collection_item = field_collection_item_load($fcid)) {
                if ($items = field_get_items('field_collection_item', $collection_item, 'field_featured_video')) {
                  foreach ($items as $item) {
                    if ($item['target_id'] != $node->nid) {
                      if ($video = node_load($item['target_id'])) {
                        $exclude[$video->nid] = $video->nid;
                        $node->content['related'][] = node_view($video, 'collection');
                        $count++;
                        if ($count >= 3) {
                          break;
                        }
                      }
                    }
                  }
                }
              }
            }
            if ($count < 3) {

              $query = db_select('node', 'n');
              $query->join('field_data_field_radio_air_date', 'rad', "(rad.entity_id = n.nid AND entity_type ='node' AND deleted = 0)");
              $query
                ->fields('n', array('nid'))
                ->condition('n.status', 1)
                ->condition('n.type', 'video')
                ->condition('n.nid', $exclude, 'NOT IN')
                ->condition('rad.field_radio_air_date_value', date('c'), '<')
                ->orderBy('rad.field_radio_air_date_value', 'DESC')
                ->range(0, (3 - $count));
              if ($nids = $query->execute()->fetchCol()) {
                foreach ($nids as $nid) {
                  if ($video = node_load($nid)) {
                    $node->content['related'][] = node_view($video, 'collection');
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  elseif ($node->type == 'pick') {
    if ($collection = tal_recommendation_get_pick_collection()) {
      $node->content['view_all'] = array(
        '#markup' => l(t('View all Monthly Staff Picks'), 'node/'.$collection->nid, array('attributes' => array('class' => array('view-all')))),
      );
    }
  }
}
