<?php
/**
 * @file
 * Code for the Extra feature.
 */

include_once 'tal_extra.features.inc';

/**
* undocumented function
*/
function tal_form_video_node_form_alter(&$form, &$form_state) {
  $node = $form['#node'];
  if ($items = field_get_items('node', $node, 'field_video')) {
    $form['field_embed']['#access'] = false;
  }
}

function tal_extra_node_presave($node) {
  if ($node->type == 'video') {
    if ($items = field_get_items('node', $node, 'field_video')) {
      if ($data = tal_oembed($items[0]['value'])) {
        $node->field_embed[LANGUAGE_NONE][0]['value'] = $data->html;
      }
    }
  }
}

function tal_extra_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'video') {
    if ($view_mode == 'full') {
      if ($items = field_get_items('node', $node, 'field_embed')) {
        $node->content['video'] = array(
          '#markup' => $items[0]['value'],
        );
      }
      else if ($items = field_get_items('node', $node, 'field_video')) {
        if ($data = tal_oembed($items[0]['value'])) {
          $node->content['video'] = array(
            '#markup' => $data->html,
          );
          $node->field_embed[LANGUAGE_NONE][0]['value'] = $data->html;
          //node_save($node);
        }
      }
    }
  }
  if ($node->type == 'article') {
    if ($view_mode == 'full') {
      if (!empty($node->content['body'][0]['#markup'])) {
        $body = $node->content['body'][0]['#markup'];
        $related = false;
        $replace = render($node->content['field_episodes']);
        if (preg_match_all('/<p>\[(?!\/)(\w*)([^\]]+)?\](([^\[]*)\[\/\1\])?<\/p>/uis', $body, $matches, PREG_SET_ORDER)) {
          foreach ($matches as $match) {
            switch ($match[1]) {
              case 'episode':
              case 'episodes':
              case 'related':
              case 'related-episode':
              case 'related_episode':
              case 'related-episodes':
              case 'related_episodes':
              $related = true;
              $find = $match[0];
              $body = str_replace($find, $replace, $body);
              break;
            }
          }
        }
        if (!$related) {
          if (preg_match('/<\/p>\s+/', $body, $matches, PREG_OFFSET_CAPTURE)) {
            $position = $matches[0][1]+4;
            $body = substr_replace($body, $replace, $position, 0);
          }
        }
        $node->content['body'][0]['#markup'] = $body;
      }
    }
  }
}
