<?php
/**
 * @file
 * Code for the Welcome feature.
 */

include_once 'tal_welcome.features.inc';

function tal_welcome_permission() {
  return array(
    'generate welcome codes' => array(
      'title' => t('Generate Welcome Codes'),
      'description' => t('Generate new codes for Welcome nodes.'),
    ),
  );
}

/**
* Implementation of hook_menu().
*/
function tal_welcome_menu() {
  $items = array();

  $items['node/%node/welcome/generate'] = array(
    'title' => t('Heartbeat'),
    'page callback' => 'tal_welcome_generate_codes',
    'page arguments' => array(1),
    'access callback' => 'tal_welcome_episode_access',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function tal_welcome_episode_access($node) {
  if ($node->type == 'welcome') {
    return user_access('generate welcome codes');
  }
  return false;
}

function tal_welcome_generate_codes($node) {
  if (!empty($_GET['station'])) {
    $count = 500;
    $station = substr(preg_replace('/\s+/', '', strtolower(filter_xss($_GET['station'], array()))), 0, 32);
    // TODO Check for existing station records
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename=welcome_'.$station.'.csv');
    $output = fopen('php://output', 'w');
    fputcsv($output, array('Count', 'Code'));
    for ($i = 1; $i <= $count; $i++) {
      $data = array(
        'id' => $i,
        'nid' => $node->nid,
        'station' => $station,
      );
      $data['sid'] = md5(uniqid(implode('', $data)));
      $data['generated'] = REQUEST_TIME;
      drupal_write_record('tal_welcome_codes', $data);
      fputcsv($output, array($data['id'], $data['sid']));
    }
    fclose($output);
    drupal_exit();
  }
  drupal_not_found();
}


function tal_welcome_custom_theme() {
  if ($node = menu_get_object()) {
    if ($node->type == 'welcome' && arg(2) != 'edit') {
      return 'welcome';
    }
  }
}

function tal_welcome_check_code($node, $code) {
  if ($result = db_query("SELECT * FROM {tal_welcome_codes} WHERE sid = :sid AND nid = :nid", array(':sid' => $code, ':nid' => $node->nid))->fetchObject()) {
    if (empty($result->activated)) {
      $result->activated = REQUEST_TIME;
      drupal_write_record('tal_welcome_codes', $result, array('sid', 'nid'));
    }
    return true;
  }
  return false;
}

function tal_welcome_code_form($form, &$form_state, $node) {
  $form['#node'] = $node;
  $form['intro'] = array(
    '#markup' => check_markup(t("Thank you for donating to your public radio station. Please enter your code to unlock the collection of Ira's favorite episodes.")),
  );
  $form['code'] = array(
    '#type' => 'textfield',
    '#title' => t('Code'),
    '#title_display' => 'invisible',
    '#required' => true,
    '#attributes' => array(
      'placeholder' => t('Enter Your Code'),
    ),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Unlock'),
    '#prefix' => '<button><span></span>',
    '#suffix' => '</button>',
  );
  return $form;
}

function tal_welcome_code_form_validate($form, &$form_state) {
  $node = $form['#node'];
  $values = $form_state['values'];
  if (!empty($values['code'])) {
    if (!tal_welcome_check_code($node, $values['code'])) {
      form_set_error('code', t('Your code was invalid.'));
    }
  }
}


function tal_welcome_code_form_submit($form, &$form_state) {
  $node = $form['#node'];
  $values = $form_state['values'];
  if (!empty($values['code'])) {
    if (tal_welcome_check_code($node, $values['code'])) {
      setcookie('tal_welcome_code', $values['code'], REQUEST_TIME+60*60*24*365, '/');
    }
  }
  $form_state['redirect'] = 'node/'.$node->nid;
}

function tal_welcome_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'welcome' && $view_mode == 'full') {
    $access = false;
    // TODO Check for cookie
    if (!empty($_COOKIE['tal_welcome_code'])) {
      $access = tal_welcome_check_code($node, $_COOKIE['tal_welcome_code']);
    }
    if ($access) {
      $data = &drupal_static(__FUNCTION__);
      if ($data = cache_get('tal_welcome:nodes:'.$node->nid)) {
        $nodes = $data->data;
      }
      else {
        $nodes = array();
        $episodes = array(27, 38, 47, 54, 61, 75, 84, 90, 93, 109, 110, 165, 172, 175, 181, 192, 199, 203, 206, 218, 220, 241, 253, 266, 268, 281, 304, 339, 355, 360, 443, 472, 484, 487, 488, 492, 504, 513, 528, 545, 550, 561, 562, 589, 600, 619, 638, 640, 647, 704);
        foreach ($episodes as $episode_number) {
          if ($episode = tal_episode_number_load($episode_number)) {
            $nodes[] = $episode;
          }
        }
        $view = node_view_multiple($nodes, 'teaser');
        $nodes = render($view);
        cache_set('tal_welcome:nodes:'.$node->nid, $nodes, 'cache', REQUEST_TIME + (60*60));
      }
      $node->content['nodes'] = array(
        '#markup' => $nodes,
      );
    }
    else {
      unset($node->content['body']);
      $node->content['code'] = drupal_get_form('tal_welcome_code_form', $node);
      /*
      $node->content['body'] = array(
        '#markup' => check_markup(t("Thank you for donating to your public radio station. Please enter your code to unlock the collection of Ira's favorite episodes.")),
      );
      */
    }
  }
}
